package com.jrock.infinity.dimension;

import com.jrock.infinity.block.BoxOfInfiniteBooksBlock;
import net.minecraft.core.component.DataComponents;
import net.minecraft.server.network.Filterable;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.component.WrittenBookContent;

import java.util.List;
import java.util.Locale;

/**
 * Derives a dimension ID from a Written Book, matching the 20w14∞ encoding.
 *
 * <h3>Box of Infinite Books</h3>
 * Books generated by {@link BoxOfInfiniteBooksBlock} contain 16 pages, each
 * holding exactly 2 lower-case hex characters.  Concatenating all 16 pages
 * yields the 32-character MD5 hex string that is the dimension ID.
 *
 * <h3>Hand-written books — named dimension exact match</h3>
 * If the book's title (trimmed, lowercased) exactly matches a known
 * {@link NamedDimension} ID, that dimension is used directly.
 *
 * <h3>Hand-written books — content hash fallback</h3>
 * If the title does not exactly match a named dimension, the dimension ID is
 * derived from the MD5 hash of the full page content (all pages concatenated,
 * lowercased, spaces and punctuation preserved).  The title is ignored.
 * Same page content always produces the same dimension.
 */
public final class DimensionHasher {

    private DimensionHasher() {}

    /**
     * Returns the dimension ID path for the given Written Book stack,
     * or {@code null} if the stack is not a valid Written Book.
     */
    public static String dimensionIdFor(ItemStack stack) {
        if (!stack.is(Items.WRITTEN_BOOK)) return null;

        WrittenBookContent book = stack.get(DataComponents.WRITTEN_BOOK_CONTENT);
        if (book == null) return null;

        String title = book.title().raw();
        if (title == null || title.isBlank()) return null;

        List<Filterable<Component>> pages = book.pages();

        // ── Box of Infinite Books: 16-page hex encoding ───────────────────────
        if (pages.size() == 16) {
            StringBuilder sb = new StringBuilder(32);
            for (Filterable<Component> page : pages) {
                sb.append(page.raw().getString());
            }
            String hexId = sb.toString();
            if (hexId.matches("[0-9a-f]{32}")) {
                return hexId;
            }
        }

        // ── Hand-written book: exact title match for named dimensions ────────
        String normalizedTitle = title.trim().toLowerCase(Locale.ROOT);
        if (NamedDimension.isNamed(normalizedTitle)) return normalizedTitle;

        // ── Hand-written book: hash the page content ──────────────────────────
        StringBuilder content = new StringBuilder();
        for (Filterable<Component> page : pages) {
            content.append(page.raw().getString());
        }
        return BoxOfInfiniteBooksBlock.md5Hex(content.toString().toLowerCase(Locale.ROOT));
    }
}
